<div>
    <img src="https://scontent.fhan4-1.fna.fbcdn.net/v/t1.0-9/152331210_844675579413594_8768301775422889325_o.jpg?_nc_cat=104&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=1auIM2Zhej4AX8XkpRv&_nc_ht=scontent.fhan4-1.fna&oh=8213374412c9cb76bfbddccf485b573f&oe=606E34CB">
</div>
<div>
    <ul>
        <li>Họ và tên: Nguyễn Văn Đạo</li>
        <li>Tuổi: 20</li>
        <li>Ngày sinh: 22/03/2000</li>
        <li>Sinh viên năm 3 - Đại học Bách Khoa Hà Nội</li>
    </ul>
</div>
